// devtools_recorder: record browser_* actions into a flow, parameterize, add assertions/checkpoints, replay.
import { z } from 'zod';
import { type Ctx, tool, tabArg, text, currentClient } from '../context.ts';
import { writeFileSync } from 'node:fs';
import { saveArtifact, listArtifacts, readArtifact } from '../artifacts.ts';

/** Recorded flow → Playwright test. Selectors were captured at record time; {{params}} become env vars. */
export function toPlaywright(f: Flow): string {
  const q = (v: unknown) => JSON.stringify(v).replace(/"\{\{(\w+)\}\}"/g, (_, p) => `(process.env.${p.toUpperCase()} ?? '')`);
  const loc = (s: Step) => (s.selector ? `page.locator(${q(s.selector)})` : `page.locator('TODO: no selector recorded')`);
  const KEY: Record<string, string> = { Meta: 'Meta', Control: 'Control', Alt: 'Alt', Shift: 'Shift' };
  const lines = f.steps.map((s) => {
    const a = (s.args ?? {}) as Record<string, any>;
    if (s.checkpoint) return `  // checkpoint: ${s.checkpoint}`;
    switch (s.tool) {
      case 'browser_navigate': return a.action === 'goto' ? `  await page.goto(${q(a.url)});` : a.action === 'reload' ? '  await page.reload();' : a.action === 'back' ? '  await page.goBack();' : '  await page.goForward();';
      case 'browser_click': return a.hover ? `  await ${loc(s)}.hover();` : a.dragTo ? `  // drag recorded; adjust target locator\n  await ${loc(s)}.dragTo(page.locator('TODO'));` : `  await ${loc(s)}.click(${a.button || a.count ? q({ ...(a.button && { button: a.button }), ...(a.count && { clickCount: a.count }) }) : ''});`;
      case 'browser_fill': return `  await ${loc(s)}.fill(${q(a.text)});`;
      case 'browser_select': return `  await ${loc(s)}.selectOption(${q(a.values)});`;
      case 'browser_key': return a.key ? `  await page.keyboard.press(${q(String(a.key).split('+').map((k: string) => KEY[k] ?? k).join('+'))});` : `  await page.keyboard.type(${q(a.text)});`;
      case 'browser_wait': {
        if (a.text) return `  await expect(page.getByText(${q(a.text)}).first()).toBeVisible();`;
        if (a.textGone) return `  await expect(page.getByText(${q(a.textGone)})).toHaveCount(0);`;
        if (a.url) return `  await expect(page).toHaveURL(new RegExp(${q(String(a.url).replace(/[.*+?^${}()|[\]\\]/g, '\\\\$&'))}));`;
        if (s.selector) return `  await expect(${loc(s)}).${a.state === 'hidden' ? 'toBeHidden' : a.state === 'enabled' ? 'toBeEnabled' : 'toBeVisible'}();`;
        return '  // wait step without a checkable condition';
      }
      default: return `  // ${s.tool} ${q(a)}`;
    }
  });
  return `import { test, expect } from '@playwright/test';\n\n// Generated by browspark from flow "${f.name}" (${f.createdAt})${f.params.length ? `\n// Params: ${f.params.map((p) => `${p.toUpperCase()}=…`).join(' ')}` : ''}\ntest(${q(f.name)}, async ({ page }) => {\n${lines.join('\n')}\n});\n`;
}

export interface Step { tool?: string; args?: Record<string, unknown>; selector?: string; checkpoint?: string; note?: string }
export interface Flow { id: string; name: string; createdAt: string; params: string[]; steps: Step[] }

const MAX_FLOWS = 50;

class Recorder {
  flows = new Map<string, Flow>();
  setFlow(f: Flow) {
    if (this.flows.size >= MAX_FLOWS) {
      const oldest = this.flows.keys().next().value;
      if (oldest) this.flows.delete(oldest);
    }
    this.flows.set(f.id, f);
  }
  /** Records into the recording of the agent making the call, if it is recording this tab. */
  record(tabId: number, toolName: string, args: Record<string, unknown>) {
    const active = currentClient()?.recording;
    if (!active || active.tabId !== tabId) return;
    const { selector, ...rest } = args;
    const clean = Object.fromEntries(Object.entries(rest).filter(([, v]) => v !== undefined));
    active.steps.push({ tool: toolName, args: clean, ...(typeof selector === 'string' && { selector }) });
  }
}
export const recorder = new Recorder();

const subst = (v: unknown, params: Record<string, string>): unknown => typeof v === 'string' ? v.replace(/\{\{(\w+)\}\}/g, (_, k) => (k in params ? params[k] : `{{${k}}}`)) : Array.isArray(v) ? v.map((x) => subst(x, params)) : v && typeof v === 'object' ? Object.fromEntries(Object.entries(v).map(([k, x]) => [k, subst(x, params)])) : v;
const paramsIn = (steps: Step[]) => [...new Set(JSON.stringify(steps).match(/\{\{(\w+)\}\}/g)?.map((m) => m.slice(2, -2)) ?? [])];

export function registerRecorderTools(ctx: Ctx) {
  const { sessions, page, registry } = ctx;
  const tab = (id?: number) => sessions.resolve(id);
  const me = () => ctx.client;
  const loadFlow = (idOrPath?: string) => {
    if (!idOrPath) throw new Error('flowId required');
    const mem = recorder.flows.get(idOrPath); if (mem) return mem;
    const raw = readArtifact(idOrPath); const f = JSON.parse(raw) as Flow; recorder.setFlow(f); return f;
  };

  tool(ctx, 'devtools_recorder', 'Record and replay browser actions. start records every browser_navigate/click/fill/select/key/wait on the tab (with a stable selector per element); stop saves the flow as a JSON artifact. add_assertion appends a browser_wait check; add_checkpoint marks a place replay can stop at; parameterize turns a recorded literal into {{name}}. replay runs a flow on a tab with params, resolving selectors to fresh refs, and stops at the first failure or at stopAtCheckpoint.', {
    action: z.enum(['start', 'stop', 'status', 'list', 'get', 'add_assertion', 'add_checkpoint', 'parameterize', 'replay', 'delete_step', 'export']),
    format: z.enum(['playwright']).optional().describe('export: target format (Playwright TypeScript test)'), path: z.string().optional().describe('export: also write the file here'),
    tabId: tabArg, name: z.string().optional(), flowId: z.string().optional().describe('Flow id or artifact path'),
    assertion: z.object({ text: z.string().optional(), textGone: z.string().optional(), url: z.string().optional(), selector: z.string().optional(), state: z.enum(['visible', 'hidden', 'enabled']).optional(), timeoutMs: z.number().int().optional() }).optional(),
    label: z.string().optional().describe('Checkpoint label'), stepIndex: z.number().int().optional(), field: z.string().optional().describe('Arg to parameterize, e.g. "text" or "url"'), paramName: z.string().optional(),
    params: z.record(z.string(), z.string()).optional(), stopAtCheckpoint: z.string().optional(), fromStep: z.number().int().optional(), continueOnFailure: z.boolean().optional(),
  }, async (a) => {
    switch (a.action) {
      case 'start': { const id = await tab(a.tabId); if (me().recording) throw new Error(`Already recording "${me().recording!.name}" on tab ${me().recording!.tabId}; stop it first.`); me().recording = { tabId: id, name: a.name ?? `flow-${Date.now()}`, steps: [], startedAt: Date.now() }; const url = await page.evaluate<string>(id, 'location.href').catch(() => undefined); if (url) me().recording!.steps.push({ tool: 'browser_navigate', args: { action: 'goto', url } }); return `Recording "${me().recording!.name}" on tab ${id}. Perform actions with the browser_* tools, then stop.`; }
      case 'status': { const r = me().recording; return r ? { recording: true, name: r.name, tabId: r.tabId, steps: r.steps.length } : { recording: false }; }
      case 'stop': {
        if (!me().recording) throw new Error('Not recording');
        const r = me().recording!; me().recording = undefined;
        const flow: Flow = { id: r.name.replace(/[^a-z0-9_-]+/gi, '_'), name: r.name, createdAt: new Date().toISOString(), params: paramsIn(r.steps), steps: r.steps };
        recorder.setFlow(flow);
        const art = saveArtifact('flow', 'json', JSON.stringify(flow, null, 1), flow.id);
        return `Saved flow "${flow.name}" (${flow.steps.length} steps) as ${flow.id} → ${art.path}`;
      }
      case 'list': return { inMemory: [...recorder.flows.values()].map((f) => ({ id: f.id, name: f.name, steps: f.steps.length, params: f.params })), artifacts: listArtifacts().filter((x) => x.id.includes('-flow-')).map((x) => x.path) };
      case 'get': { const f = a.flowId ? loadFlow(a.flowId) : me().recording && { ...me().recording!, id: '(recording)', params: paramsIn(me().recording!.steps), createdAt: '' }; if (!f) throw new Error('flowId required (or start recording)'); return { ...f, steps: f.steps.map((s, i) => ({ index: i, ...s })) }; }
      case 'add_assertion': case 'add_checkpoint': case 'parameterize': case 'delete_step': {
        const steps = a.flowId ? loadFlow(a.flowId).steps : me().recording?.steps; if (!steps) throw new Error('flowId required (or be recording)');
        if (a.action === 'add_checkpoint') { steps.push({ checkpoint: a.label ?? `checkpoint-${steps.length}` }); return `Checkpoint "${steps.at(-1)!.checkpoint}" added at step ${steps.length - 1}`; }
        if (a.action === 'add_assertion') { if (!a.assertion) throw new Error('assertion required'); const { selector, ...rest } = a.assertion; steps.push({ tool: 'browser_wait', args: rest, ...(selector && { selector }), note: 'assertion' }); return `Assertion added at step ${steps.length - 1}`; }
        if (a.action === 'delete_step') { if (a.stepIndex === undefined || !steps[a.stepIndex]) throw new Error('valid stepIndex required'); steps.splice(a.stepIndex, 1); return `Deleted step ${a.stepIndex}`; }
        const s = a.stepIndex !== undefined ? steps[a.stepIndex] : undefined; if (!s?.args || !a.field || !a.paramName) throw new Error('stepIndex, field, paramName required');
        const old = s.args[a.field]; s.args[a.field] = `{{${a.paramName}}}`;
        if (a.flowId) { const f = loadFlow(a.flowId); f.params = paramsIn(f.steps); }
        return `Step ${a.stepIndex} ${a.field}: ${JSON.stringify(old)} → {{${a.paramName}}}`;
      }
      case 'export': {
        const f = loadFlow(a.flowId);
        const code = toPlaywright(f);
        const art = saveArtifact('flow', 'spec.ts', code, f.id);
        if (a.path) writeFileSync(a.path, code);
        return `Wrote Playwright test for "${f.name}" (${f.steps.length} steps) to ${a.path ?? art.path}. Run with: bunx playwright test ${a.path ?? art.path}${f.params.length ? `\nParams become env vars: ${f.params.map((p) => p.toUpperCase()).join(', ')}` : ''}`;
      }
      case 'replay': {
        const f = loadFlow(a.flowId); const id = await tab(a.tabId);
        const missing = f.params.filter((p) => !(a.params ?? {})[p]); if (missing.length) throw new Error(`Missing params: ${missing.join(', ')}`);
        const log: string[] = []; let failed = false;
        for (let i = a.fromStep ?? 0; i < f.steps.length; i++) {
          const s = f.steps[i];
          if (s.checkpoint) { log.push(`${i}. ▸ checkpoint ${s.checkpoint}`); if (a.stopAtCheckpoint === s.checkpoint) { log.push(`Stopped at checkpoint "${s.checkpoint}" (resume with fromStep:${i + 1}).`); break; } continue; }
          const fn = registry.get(s.tool!); if (!fn) { log.push(`${i}. unknown tool ${s.tool}`); failed = true; break; }
          const args: Record<string, unknown> = { ...(subst(s.args, a.params ?? {}) as object), tabId: id };
          if (s.selector) { try { args.ref = await page.refFromSelector(id, s.selector); } catch (e) { log.push(`${i}. ${s.tool}: ✗ ${(e as Error).message}`); failed = true; if (!a.continueOnFailure) break; else continue; } }
          const r = await fn(args);
          const t = r.content.filter((c) => c.type === 'text').map((c) => (c as { text: string }).text).join(' ');
          log.push(`${i}. ${s.tool}${s.note ? ` (${s.note})` : ''}: ${r.isError ? '✗ ' : ''}${t.slice(0, 200)}`);
          if (r.isError) { failed = true; if (!a.continueOnFailure) { log.push(`Stopped at step ${i} (resume with fromStep:${i + 1} after fixing).`); break; } }
        }
        return { ...text(log.join('\n')), isError: failed };
      }
    }
  });
}
