// Generates docs/tools/**/*.mdx (one page per MCP tool) from the live tool registrations, and refreshes the tool
// groups in docs/docs.json. Run with `bun run docs:tools` after changing a tool's description or schema.
import { z } from 'zod';
import { mkdirSync, writeFileSync, readFileSync, rmSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { registerBrowserTools } from '../src/tools.ts';
import { registerSessionTools } from '../src/devtools/session.ts';
import { registerConsoleTools } from '../src/devtools/console.ts';
import { registerNetworkTools } from '../src/devtools/network.ts';
import { registerSourcesTools } from '../src/devtools/sources.ts';
import { registerDebuggerTools } from '../src/devtools/debugger.ts';
import { registerElementsTools } from '../src/devtools/elements.ts';
import { registerProfilingTools } from '../src/devtools/profiling.ts';
import { registerApplicationTools } from '../src/devtools/application.ts';
import { registerEnvironmentTools } from '../src/devtools/environment.ts';
import { registerLighthouseTools } from '../src/devtools/lighthouse.ts';
import { registerRecorderTools } from '../src/devtools/recorder.ts';
import { registerAuditTools } from '../src/devtools/audit.ts';
import { fileURLToPath } from 'node:url';
import { EXAMPLES, NOTES } from './docs-examples.ts';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');
const DOCS = join(ROOT, 'docs');

type Tool = { name: string; description: string; schema: any };
const tools: Tool[] = [];
const invalid: string[] = [];
const noop = { on() {} };
const ctx: any = { registry: new Map(), client: { id: 'docs', name: 'docs', ownedTabs: new Set() }, sessions: noop, page: noop, capture: noop,
  server: { registerTool: (name: string, def: any) => {
    const shape = z.object(def.inputSchema);
    // Every documented example must be a valid call, so the docs cannot drift from the schema.
    const ex = EXAMPLES[name]; const list = ex === undefined ? [] : Array.isArray(ex) ? ex.map((e) => e.args) : [ex];
    for (const args of list) { const r = shape.safeParse(args); if (!r.success) invalid.push(`${name} ${JSON.stringify(args)}: ${r.error.issues.map((i) => `${i.path.join('.')}: ${i.message}`).join('; ')}`); }
    tools.push({ name, description: def.description, schema: z.toJSONSchema(shape, { unrepresentable: 'any' }) });
  } } };
for (const reg of [registerBrowserTools, registerSessionTools, registerConsoleTools, registerNetworkTools, registerSourcesTools, registerDebuggerTools, registerElementsTools, registerProfilingTools, registerApplicationTools, registerEnvironmentTools, registerLighthouseTools, registerRecorderTools, registerAuditTools]) reg(ctx);

if (invalid.length) { console.error('invalid examples:\n' + invalid.join('\n')); process.exit(1); }

const typeOf = (p: any): string => {
  if (p.enum) return 'enum';
  if (p.anyOf) return p.anyOf.map(typeOf).join(' | ');
  if (p.type === 'array') return `${p.items ? typeOf(p.items) : 'any'}[]`;
  return p.type ?? 'any';
};
const esc = (s: string) => s.replace(/[<>{}]/g, (c) => ({ '<': '&lt;', '>': '&gt;', '{': '&#123;', '}': '&#125;' }[c]!));
const attr = (s: string) => s.replace(/"/g, '&quot;');

function page(t: Tool): string {
  const group = t.name.startsWith('browser_') ? 'browser' : 'devtools';
  const props = t.schema.properties ?? {};
  const required = new Set<string>(t.schema.required ?? []);
  const summary = t.description.split(/(?<=\.)\s/)[0]!.slice(0, 160).replace(/[<>]/g, '');
  const params = Object.entries(props).map(([name, p]: [string, any]) => {
    const bits: string[] = [];
    if (p.description) bits.push(esc(p.description));
    if (p.enum) bits.push(`One of: ${p.enum.map((v: string) => `\`${v}\``).join(', ')}.`);
    if (p.items?.enum) bits.push(`Items: ${p.items.enum.map((v: string) => `\`${v}\``).join(', ')}.`);
    if (p.items?.properties) bits.push(`Each item: ${Object.keys(p.items.properties).map((k) => `\`${k}\``).join(', ')}.`);
    const bounded = (v: number | undefined) => v !== undefined && Math.abs(v) < Number.MAX_SAFE_INTEGER;
    if (bounded(p.minimum) || bounded(p.maximum)) bits.push(`Range: ${bounded(p.minimum) ? p.minimum : '…'} to ${bounded(p.maximum) ? p.maximum : '…'}.`);
    const def = p.default !== undefined ? ` default="${attr(typeof p.default === 'string' ? p.default : JSON.stringify(p.default))}"` : '';
    return `<ParamField body="${name}" type="${typeOf(p)}"${required.has(name) ? ' required' : ''}${def}>\n  ${bits.join(' ') || '&nbsp;'}\n</ParamField>`;
  });
  const example = EXAMPLES[t.name];
  const note = NOTES[t.name];
  return `---
title: "${t.name}"
description: "${attr(summary)}"
---

{/* Generated by \`bun run docs:tools\` from companion/src. Edit descriptions in the source, examples in companion/test/docs-examples.ts. */}

${esc(t.description)}

<Note>The tool names stay the same across browsers. See [browser selection](/reference/multiple-browsers) and [Firefox and Zen exceptions](/reference/firefox) before choosing an operation.</Note>

${note ? `<Note>${note}</Note>\n` : ''}
## Parameters

${params.length ? params.join('\n\n') : 'This tool takes no parameters.'}

${example ? `## Example\n\n${Array.isArray(example) ? example.map((e) => `\`\`\`json ${e.title ?? ''}\n${JSON.stringify(e.args, null, 2)}\n\`\`\`${e.text ? `\n\n${e.text}` : ''}`).join('\n\n') : `\`\`\`json\n${JSON.stringify(example, null, 2)}\n\`\`\``}` : ''}
`;
}

for (const g of ['browser', 'devtools']) rmSync(join(DOCS, 'tools', g), { recursive: true, force: true });
for (const t of tools) {
  const group = t.name.startsWith('browser_') ? 'browser' : 'devtools';
  const file = join(DOCS, 'tools', group, `${t.name}.mdx`);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, page(t));
}

// Keep the navigation in docs.json in sync with the registered tools.
const cfgPath = join(DOCS, 'docs.json');
const cfg = JSON.parse(readFileSync(cfgPath, 'utf8'));
const walk = (node: any): void => {
  if (Array.isArray(node)) return node.forEach(walk);
  if (node && typeof node === 'object') {
    if (node.group === 'Browser automation') node.pages = ['tools/overview', ...tools.filter((t) => t.name.startsWith('browser_')).map((t) => `tools/browser/${t.name}`)];
    if (node.group === 'Developer tools') node.pages = tools.filter((t) => t.name.startsWith('devtools_')).map((t) => `tools/devtools/${t.name}`);
    Object.values(node).forEach(walk);
  }
};
walk(cfg);
writeFileSync(cfgPath, JSON.stringify(cfg, null, 2) + '\n');
console.log(`wrote ${tools.length} tool pages under docs/tools and updated docs/docs.json`);
