// Hand-written examples and notes for the generated tool reference (docs/tools). Keys are tool names.
type Ex = Record<string, unknown> | { title?: string; args: Record<string, unknown>; text?: string }[];

export const NOTES: Record<string, string> = {
  browser_session: 'Use a different context name for each running browser. Connected dashboards apply the most restrictive developer-browser setting: Never, then Only when needed, then Always. An explicit user request satisfies Only when needed.',
  devtools_cdp: 'Chromium developer mode only. Firefox, Zen and extension tabs cannot send raw CDP commands. For target:browser, specify context when several developer browsers are running.',
  devtools_lighthouse: 'Chromium developer mode only. Lighthouse opens its own tab in the selected developer browser. Pass a developer tabId to choose between running Chromium contexts. Firefox and Zen are unsupported.',
  devtools_memory: 'Heap snapshots, class diffs, retainers and allocation sampling need Chromium developer mode because extensions cannot use HeapProfiler. usage and growth also work in Chromium extension mode. Firefox and Zen do not support this tool.',
  browser_extensions: 'Extension mode only, and off until the user turns on Settings → Other extensions in the Browspark dashboard (which also needs the browser\'s management permission). Cannot read another extension\'s storage, cannot bypass externally_connectable, and never manages Browspark itself. uninstall shows the browser\'s own confirmation. Options pages are automatable only in Chromium, only when the user enables Share options pages, and the browser may still refuse the debugger; chrome://extensions and store pages stay blocked. Firefox opens options pages but cannot automate them.',
  browser_key: 'Keys reach the web page only. Browser shortcuts such as opening DevTools or switching tabs are handled by the browser UI and cannot be triggered here.',
  browser_batch: 'Each step is a normal tool call. The batch stops at the first error and returns the results collected so far.',
  devtools_audit: 'Runs in-page checks for layout overflow, broken images, WCAG accessibility, and SEO across Chromium and Firefox in both modes. Console runtime errors and network requests are inspected from active DevTools capture sessions (available in Chromium and developer-mode Firefox; Firefox extension mode does not support native capture sessions).',
};

export const EXAMPLES: Record<string, Ex> = {
  browser_status: {},
  browser_session: [
    { title: 'Launch the default context', args: { action: 'launch' } },
    { title: 'Launch because the user asked for a developer browser', args: { action: 'launch', userRequested: true } },
    { title: 'Launch Firefox in an isolated profile', args: { action: 'launch', browser: 'firefox', context: 'firefox', userRequested: true } },
    { title: 'Launch Chrome in a named context', args: { action: 'launch', browser: 'chrome', context: 'chrome-work', userRequested: true } },
    { title: 'Run Brave alongside the other contexts', args: { action: 'launch', browser: 'brave', context: 'brave-work', userRequested: true } },
    { title: 'Run Zen in its own profile', args: { action: 'launch', browser: 'zen', context: 'zen-work', userRequested: true } },
    { title: 'Launch a named, headless context behind a proxy', args: { action: 'launch', context: 'scraper', headless: true, proxy: 'socks5://127.0.0.1:1080', url: 'https://example.com' } },
    { title: 'Close everything', args: { action: 'close', all: true } },
  ],
  browser_tabs: [
    { title: 'List usable tabs', args: { action: 'list', onlyUsable: true } },
    { title: 'Open a page in the user\'s window', args: { action: 'new', url: 'https://example.com' } },
    { title: 'Choose a connected extension browser', args: { action: 'new', browserId: 'ext:example-browser-id', url: 'https://example.com' }, text: 'Use a browserId returned by browser_status or browser_tabs.' },
    { title: 'Open in a named developer context', args: { action: 'new', context: 'zen-work', url: 'https://example.com' } },
  ],
  browser_extensions: [
    { title: 'List installed extensions', args: { action: 'list' } },
    { title: 'Inspect permissions', args: { action: 'info', extensionId: 'abcdefghijklmnopabcdefghijklmnop' } },
    { title: 'Disable an extension', args: { action: 'disable', extensionId: 'abcdefghijklmnopabcdefghijklmnop' } },
    { title: 'Open an options page', args: { action: 'open', extensionId: 'abcdefghijklmnopabcdefghijklmnop' } },
    { title: 'Message a cooperating extension', args: { action: 'message', extensionId: 'abcdefghijklmnopabcdefghijklmnop', message: { type: 'ping' } }, text: 'The target must list Browspark in externally_connectable and answer in runtime.onMessageExternal.' },
  ],
  browser_navigate: [
    { args: { tabId: 1234, url: 'https://example.com/login' } },
    { title: 'Go back', args: { tabId: 1234, action: 'back' } },
  ],
  browser_snapshot: [{ args: { tabId: 1234 } }, { title: 'Only what changed since the last snapshot', args: { tabId: 1234, diff: true } }],
  browser_read: [{ title: 'Main content as markdown', args: { tabId: 1234, what: 'markdown' } }, { title: 'Tables inside one element', args: { tabId: 1234, what: 'tables', ref: 'e42' } }],
  browser_fetch: [{ title: 'Read main content', args: { url: 'https://developer.chrome.com/docs/devtools/', what: 'markdown' } }, { title: 'Read using a specific browser', args: { url: 'https://example.com', browserId: 'ext:example-browser-id' }, text: 'Use a connected browserId from browser_status.' }],
  browser_policy: [
    { title: 'Allow-list for one tab', args: { action: 'set', tabId: 1234, allow: ['example.com', 'cdn.example.net'] } },
    { title: 'Block trackers on every tab the agent opens from now on', args: { action: 'set', default: true, block: ['doubleclick.net', 'google-analytics.com'] } },
  ],
  browser_download: { action: 'wait', tabId: 1234, urlContains: 'report.csv', timeoutMs: 30000 },
  browser_pdf: { tabId: 1234, format: 'A4', printBackground: true },
  browser_webmcp: [{ args: { tabId: 1234, action: 'list' } }, { args: { tabId: 1234, action: 'invoke', name: 'searchProducts', args: { query: 'lamp' } } }],
  browser_extract: { tabId: 1234, items: '.product-card', fields: { name: 'h3', price: '.price', link: { selector: 'a', attr: 'href' } }, limit: 50 },
  browser_click: [{ args: { tabId: 1234, ref: 'e12' } }, { title: 'Hover', args: { tabId: 1234, ref: 'e12', hover: true } }, { title: 'Drag one element onto another', args: { tabId: 1234, ref: 'e12', dragTo: 'e30' } }],
  browser_fill: { tabId: 1234, ref: 'e7', text: 'jane@example.com' },
  browser_select: { tabId: 1234, ref: 'e9', values: ['Europe/Berlin'] },
  browser_upload: { tabId: 1234, ref: 'e15', files: ['/Users/me/Desktop/avatar.png'] },
  browser_key: [{ args: { tabId: 1234, key: 'Enter' } }, { title: 'Type text into the focused field', args: { tabId: 1234, text: 'hello world' } }, { title: 'Select all on macOS', args: { tabId: 1234, key: 'Meta+a' } }],
  browser_scroll: { tabId: 1234, direction: 'down', amount: 800 },
  browser_screenshot: [{ args: { tabId: 1234 } }, { title: 'Full page as JPEG', args: { tabId: 1234, fullPage: true, format: 'jpeg', quality: 70 } }, { title: 'One element', args: { tabId: 1234, ref: 'e42' } }],
  browser_wait: [{ args: { tabId: 1234, text: 'Order confirmed', timeoutMs: 20000 } }, { title: 'Until the URL changes', args: { tabId: 1234, url: '/dashboard' } }, { title: 'Until a ref is enabled', args: { tabId: 1234, ref: 'e3', state: 'enabled' } }],
  browser_dialog: { tabId: 1234, accept: true, promptText: 'yes' },
  browser_batch: { steps: [
    { tool: 'browser_navigate', args: { tabId: 1234, url: 'https://example.com/login' } },
    { tool: 'browser_snapshot', args: { tabId: 1234 } },
  ] },
  devtools_session: [{ args: { action: 'start', tabId: 1234, bodies: true } }, { title: 'Drop collected network data only', args: { action: 'clear', tabId: 1234, what: 'network' } }, { args: { action: 'stop', tabId: 1234 } }],
  devtools_events: [{ title: 'Page through collected events', args: { tabId: 1234, afterId: 0, limit: 100 } }, { title: 'Block until a request to /api fails', args: { tabId: 1234, method: 'Network.loadingFailed', text: '/api', wait: true, timeoutMs: 15000 } }],
  devtools_capabilities: { tabId: 1234 },
  devtools_cdp: [{ args: { tabId: 5001, method: 'Page.getNavigationHistory' } }, { title: 'Browser target', args: { target: 'browser', method: 'Browser.getVersion', context: 'default' } }],
  devtools_console: [
    { title: 'Errors mentioning "undefined"', args: { tabId: 1234, level: ['error'], kind: ['console', 'exception'], query: 'undefined' } },
    { title: 'Inspect a logged object', args: { tabId: 1234, action: 'inspect', id: 12, depth: 3 } },
    { title: 'Wait for a message', args: { tabId: 1234, action: 'wait', query: 'hydrated', timeoutMs: 10000 } },
  ],
  devtools_evaluate: [{ args: { tabId: 1234, expression: 'document.title' } }, { title: 'In the paused call frame', args: { tabId: 1234, expression: 'user.id', callFrameId: '{"ordinal":0,"injectedScriptId":2}' } }],
  devtools_network: [
    { title: 'Slow API calls', args: { tabId: 1234, domain: 'api.example.com', minDurationMs: 500 } },
    { title: 'Response body', args: { tabId: 1234, action: 'body', requestId: '1234.56' } },
    { title: 'Mock an endpoint', args: { tabId: 1234, action: 'mock', pattern: '*/api/user', response: { status: 200, headers: { 'content-type': 'application/json' }, body: '{"name":"Test User"}' } } },
    { title: 'Throttle to slow 3G', args: { tabId: 1234, action: 'throttle', preset: 'slow3g' } },
    { title: 'Export HAR', args: { tabId: 1234, action: 'har' } },
  ],
  devtools_sources: [
    { title: 'Search all scripts', args: { tabId: 1234, action: 'search', query: 'fetchUser', kind: 'scripts' } },
    { title: 'Original source through the source map', args: { tabId: 1234, action: 'get', url: 'https://example.com/app.js', original: true, fromLine: 1, toLine: 80 } },
    { title: 'Override a resource until the session stops', args: { tabId: 1234, action: 'override', url: 'https://example.com/config.json', body: '{"flag":true}', contentType: 'application/json', reload: true } },
  ],
  devtools_debugger: [
    { title: 'Conditional breakpoint in the original source', args: { tabId: 1234, action: 'set', source: 'src/cart.ts', line: 42, condition: 'item.qty > 1' } },
    { title: 'Break on uncaught exceptions', args: { tabId: 1234, action: 'exceptions', state: 'uncaught' } },
    { title: 'Break when a request URL contains /checkout', args: { tabId: 1234, action: 'xhr', urlSubstring: '/checkout' } },
    { title: 'While paused: stack, then step', args: { tabId: 1234, action: 'stack' } },
    { args: { tabId: 1234, action: 'stepOver' } },
  ],
  devtools_elements: [
    { title: 'Find elements', args: { tabId: 1234, action: 'search', query: 'button.primary', limit: 5 } },
    { title: 'Matched CSS rules', args: { tabId: 1234, action: 'styles', ref: 'e12' } },
    { title: 'Edit an inline style', args: { tabId: 1234, action: 'styles', ref: 'e12', property: 'color', value: 'red', important: true } },
    { title: 'Force :hover', args: { tabId: 1234, action: 'pseudo', ref: 'e12', states: ['hover'] } },
  ],
  devtools_performance: [{ args: { tabId: 1234, action: 'start', reload: true, screenshots: false } }, { args: { tabId: 1234, action: 'stop' } }, { title: 'Live Web Vitals', args: { tabId: 1234, action: 'vitals' } }],
  devtools_profile: [{ args: { tabId: 1234, action: 'start', samplingIntervalUs: 500 } }, { args: { tabId: 1234, action: 'stop', limit: 20 } }],
  devtools_memory: [{ args: { tabId: 5001, action: 'snapshot' } }, { title: 'Growth between two snapshots', args: { tabId: 5001, action: 'compare', snapshotId: 'snap-2', other: 'snap-1' } }, { title: 'Sample heap usage for 20 seconds', args: { tabId: 1234, action: 'growth', seconds: 20, gc: true } }],
  devtools_coverage: [{ args: { tabId: 1234, action: 'start', reload: true } }, { args: { tabId: 1234, action: 'stop' } }, { args: { tabId: 1234, action: 'detail', url: 'https://example.com/app.js' } }],
  devtools_storage: [
    { title: 'Cookies for the page origin', args: { tabId: 1234, area: 'cookies', action: 'list' } },
    { title: 'Set a localStorage key', args: { tabId: 1234, area: 'local', action: 'set', key: 'featureFlag', value: 'on' } },
    { title: 'Read an IndexedDB store', args: { tabId: 1234, area: 'indexeddb', action: 'data', database: 'app', store: 'todos', pageSize: 20 } },
    { title: 'Clear named storage types for the origin', args: { tabId: 1234, area: 'clear', types: ['cookies', 'local_storage'] } },
  ],
  devtools_workers: [{ args: { tabId: 1234, action: 'list' } }, { args: { tabId: 1234, action: 'bypass', enabled: true } }, { args: { tabId: 1234, action: 'manifest' } }],
  devtools_emulation: [
    { title: 'Device preset', args: { tabId: 1234, action: 'device', preset: 'iphone-14' } },
    { title: 'Custom viewport', args: { tabId: 1234, action: 'device', width: 390, height: 844, scale: 3, mobile: true, touch: true } },
    { title: 'Dark mode and reduced motion', args: { tabId: 1234, action: 'media', colorScheme: 'dark', reducedMotion: 'reduce' } },
    { title: 'Throttle the CPU 4x', args: { tabId: 1234, action: 'cpu', rate: 4 } },
    { args: { tabId: 1234, action: 'reset' } },
  ],
  devtools_accessibility: [{ args: { tabId: 1234, action: 'tree', ref: 'e12', depth: 3 } }, { args: { tabId: 1234, action: 'check' } }, { args: { tabId: 1234, action: 'issues' } }],
  devtools_security: [{ args: { tabId: 1234, action: 'state' } }, { args: { tabId: 1234, action: 'mixedContent' } }],
  devtools_lighthouse: { url: 'https://example.com', device: 'mobile', categories: ['performance', 'accessibility'] },
  devtools_recorder: [
    { args: { action: 'start', tabId: 1234, name: 'checkout' } },
    { title: 'Add an assertion while recording', args: { action: 'add_assertion', flowId: 'checkout', assertion: { text: 'Order confirmed' } } },
    { args: { action: 'stop', flowId: 'checkout' } },
    { title: 'Turn a literal into a parameter', args: { action: 'parameterize', flowId: 'checkout', stepIndex: 2, field: 'text', paramName: 'email' } },
    { title: 'Replay with parameters', args: { action: 'replay', flowId: 'checkout', tabId: 1234, params: { email: 'qa@example.com' } } },
    { title: 'Export as a Playwright test', args: { action: 'export', flowId: 'checkout', format: 'playwright', path: '/Users/me/tests/checkout.spec.ts' } },
  ],
  devtools_audit: [
    { title: 'Full 360-degree health audit of the active page', args: { tabId: 1234 } },
    { title: 'Check responsive layout and accessibility only', args: { tabId: 1234, categories: ['layout', 'accessibility'] } },
    { title: 'Errors only', args: { tabId: 1234, threshold: 'errors' } },
  ],
};
